version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: personal-blog-mysql
    restart: always
    env_file:
      - ./env/.development.env
    environment:
      TZ: Asia/Seoul
      LANG: C.UTF-8
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --authentication_policy=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: personal-blog-redis
    restart: always
    env_file:
      - ./env/.development.env
    ports:
      - "6379:6379"
    command: sh -c "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    volumes:
      - ./data/redis:/data
